nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['http://localhost:4200']
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:4200']
      allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
      max_age: 3600
